algoritmo "L02J"
// Função :
// Autor : Higor Antônio dos Santos Benevenuto
// Data : 29/08/2024
// Seção de Declarações
var
num :real
inicio
// Seção de Comandos
escreval("*** Entre a faixa de 1 a 9 ***")
escreval("")
escreva("Digite um número: ")
leia(num)

se (num >= 1) e (num <= 9) entao
   escreval("O valor está na faixa permitida.")
senao
   escreval("O valor está fora da faixa permitida.")
fimse
fimalgoritmo
