algoritmo "L01A"
// Função :
// Autor : Higor Antônio dos Santos Benevenuto
// Data : 27/08/2024
// Seção de Declarações 
var
temperaturaEmCelcius, temperaturaEmFahrenheit :real
inicio
// Seção de Comandos 
escreva("Digite a temperatura em Celcius: ")
leia(temperaturaEmCelcius)

temperaturaEmFahrenheit := (9*temperaturaEmCelcius+160)/5

escreva("A temperatura em Fahrenheit é ", temperaturaEmFahrenheit, " graus.")

fimalgoritmo
