algoritmo "L01B"
// Função :
// Autor : Higor Antônio dos Santos Benevenuto
// Data : 28/08/2024
// Seção de Declarações 
var
temperaturaEmFahrenheit, temperaturaEmCelcius :real
inicio
// Seção de Comandos 
escreva("Digite a temperatura em Fahrenheit: ")
leia(temperaturaEmFahrenheit)

temperaturaEmCelcius := (temperaturaEmFahrenheit - 32) * (5/9)

escreva("A temperatura em Celcius é: ", temperaturaEmCelcius, " graus.")
fimalgoritmo
