algoritmo "L01C"
// Função :
// Autor : Higor Antônio dos Santos Benevenuto
// Data : 28/08/2024
// Seção de Declarações 
var
volume, raio, altura :real
inicio
// Seção de Comandos 
escreva("Digite o valore do raio da lata de óleo: ")
leia(raio)

escreva("Digite o valore da altura da lata de óleo: ")
leia(altura)

volume := PI * raio ^ 2 * altura

escreva("O volume da lata de óleo é igual a: ", volume)
fimalgoritmo
