algoritmo "L01I"
// Função :
// Autor : Higor Antônio dos Santos Benevenuto
// Data : 28/08/2024
// Seção de Declarações 
var
A, B :inteiro
resultado :real
inicio
// Seção de Comandos 
escreval("Digite valores inteiros para as variáveis a seguir...")
escreva("A: ")
leia(A)
escreva("B: ")
leia(B)

resultado := (A-B)^2

escreva("O quadrado da diferença dos termos digitados é: ", resultado)
fimalgoritmo
