algoritmo "L01L"
// Função :
// Autor : Higor Antônio dos Santos Benevenuto
// Data : 28/08/2024
// Seção de Declarações 
var
A, B, C, resultado :real
inicio
// Seção de Comandos 
escreval("*** Calculadora de soma dos quadrados ***")
escreval("Digite um número inteiro para cada uma das variáveis a seguir...")
escreva("A: ")
leia(A)
escreva("B: ")
leia(B)
escreva("C: ")
leia(C)

resultado := A^2 + B^2 + C^2

escreva("A soma dos quadrados dos valores informados é: ", resultado)
fimalgoritmo
