algoritmo "L01M"
// Função :
// Autor : Higor Antônio dos Santos Benevenuto
// Data : 28/08/2024
// Seção de Declarações
var
A, B, C, resultado :real
inicio
// Seção de Comandos
escreval("*** Calculadora de quadrado da soma ***")
escreval("Digite um número inteiro para cada uma das variáveis a seguir...")
escreva("A: ")
leia(A)
escreva("B: ")
leia(B)
escreva("C: ")
leia(C)

resultado := (A+B+C)^2

escreva("O quadrado da soma dos valores informados é: ", resultado)
fimalgoritmo
